{
 "title": "IBOH Food API",
 "time": { "from": "2019-10-08T06:41:48.892Z", "to": "2019-10-10T06:41:48.894Z" },
 "templating": {
  "list": [
   { "name": "application", "query": "label_values(application)" },
   { "name": "cluster", "query": "label_values(cluster)" },
   { "name": "revision", "query": "label_values(revision)" },
   {
    "name": "endpoint",
    "query": "/actuator/info,/actuator/health,/food/order/version/{companyCode}/{storeCode}/{orderDate},/food/batchInvoicesSync,/food/order/batchAutoSubmitFoodOrders,/food/distributor_order_delivery_by_store/,/food/item"
   }
  ]
 },
 "panels": [
  { "title": "File descriptors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "File descriptor utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files{application=\"$application\", cluster=~\"$cluster\", revision=~\"$revision\"} / process_files_max_files{application=\"$application\", cluster=~\"$cluster\", revision=~\"$revision\"}",
     "legendFormat": "v{{revision}} {{host}}"
    }
   ]
  },
  { "title": "Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Process CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(5,process_cpu_usage{application=~\"$application\", cluster=~\"$cluster\", revision=~\"$revision\"})",
     "legendFormat": "v{{revision}} {{host}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", cluster=~\"$cluster\", revision=~\"$revision\", area=\"heap\", id!=\"PS Survivor Space\"}) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Promotion/Allocation Ratio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(5, jvm_gc_memory_promoted_bytes_total{application=~\"$application\", cluster=~\"$cluster\", revision=~\"$revision\"} / jvm_gc_memory_allocated_bytes_total{application=~\"$application\", cluster=~\"$cluster\", revision=~\"$revision\"})",
     "legendFormat": "v{{revision}} {{host}}"
    }
   ]
  },
  {
   "title": "Top GC Event Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(2,jvm_gc_pause_seconds_max{application=\"$application\", cluster=~\"$cluster\", revision=~\"$revision\"})",
     "legendFormat": "v{{revision}} {{host}} ({{action}})"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency $endpoint",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_bucket{application=~\"$application\", cluster=~\"$cluster\", revision=~\"$revision\", uri=\"$endpoint\", status=\"200\", le=~\"0\\\\.[0-4]\\\\d+|\\\\+Inf\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Latency $endpoint",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(http_server_requests_seconds_max{application=~\"$application\", cluster=~\"$cluster\", revision=~\"$revision\", uri=\"$endpoint\"})",
       "legendFormat": "max"
      },
      {
       "expr": "histogram_quantile(0.99, max(rate(http_server_requests_seconds_bucket{application=~\"$application\", cluster=~\"$cluster\", revision=~\"$revision\", uri=\"$endpoint\"}[2m])) by (le))",
       "legendFormat": "P99"
      }
     ]
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Error ratio",
   "type": "graph",
   "description": "Errors as a function of throughput, so that we understand the proportionality of errors relative to the total traffic coming through the system.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=~\"$application\",cluster=~\"$cluster\",revision=~\"$revision\",uri=\"$endpoint\",outcome!=\"SUCCESS\"}[1m])/rate(http_server_requests_seconds_count{application=~\"$application\",cluster=~\"$cluster\",revision=~\"$revision\",uri=\"$endpoint\"}[1m])",
     "legendFormat": "v{{revision}} {{host}} ({{status}})"
    }
   ]
  }
 ]
}